version: "3.8"
services:
    mysql_db:
        build: mysqllocker
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: "YTLockerDB"
            MYSQL_TCP_PORT: 3306
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
        expose:
            - 3306
        volumes:
            - ../my-data:/var/lib/mysql
        networks:
            - default

    golang_api:
        build: golocker
        volumes:
            - ./golocker:/go/src/golocker
        ports:
            - 8080:8080
        environment:
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_HOST: "172.26.0.1"
            MYSQL_TCP_PORT: 3306
            MYSQL_DATABASE: "YTLockerDB"
            YOUTUBE_API_KEY: ""
            GO_API_HOST: ""
            GO_API_PORT: "8080"
            ADMIN_BEARER: "TEMP_ADMIN_BEARER"
            WEB_URL: "https://ytlocker.com"
        networks:
            - default

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.26.0.0/16
                  gateway: 172.26.0.1
