version: "3.8"
services:
    db:
        build:
            mysqllocker
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_DATABASE: "YTLockerDB"
            MYSQL_ALLOW_EMPTY_PASSWORD: "NO"
            MYSQL_TCP_PORT: 3306
            MYSQL_USER: ""
            MYSQL_PASSWORD: ""
        expose:
            - 3306
        networks:
            - default
    api:
        build:
            golocker
        depends_on: 
            - db
        volumes:
            - ./golocker:/go/src/golocker
        ports:
            - 8080:8080
        environment:
            MYSQL_USER: ""
            MYSQL_PASSWORD: ""
            MYSQL_HOST: "172.26.0.1"
            MYSQL_TCP_PORT: 3306
            MYSQL_DATABASE: "YTLockerDB"
            YOUTUBE_API_KEY: ""
            GO_API_HOST: ""
            GO_API_PORT: "8080"
        networks:
            - default


networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.26.0.0/16
                  gateway: 172.26.0.1
