version: "3.8"
services:
    api:
        build:
            golocker
        volumes:
            - ./golocker:/go/src/app
        ports:
            - 8080:8080
        env_file:
            - .env
        expose:
            - 8080
        command: ["go", "run", "main.go"]
        environment:
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "password"
            MYSQL_HOST: ""
            MYSQL_TCP_PORT: 3306
            MYSQL_DATABASE: "YTLockerDB"
            YOUTUBE_API_KEY: ""
            GO_API_HOST: ""
            GO_API_PORT: "8080"
