version: "3.8"
services:
    mysql_db:
        build:
            mysqllocker
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: "YTLockerDB"
            MYSQL_TCP_PORT: 3306
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
        expose:
            - 3306
        volumes:
            - ../my-data:/var/lib/mysql
        networks:
            - default

    test_db:
        build:
            mysqllocker
        restart: always
        ports:
            - 9906:9906
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: "YTLockerDB"
            MYSQL_TCP_PORT: 9906
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
        expose:
            - 9906
        networks:
            - default
        tmpfs:
            - /var/lib/mysql

    golang_api:
        build:
            golocker
        depends_on: 
            - mysql_db
        volumes:
            - ./golocker:/go/src/golocker
        ports:
            - 8080:8080
        environment:
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_HOST: "172.26.0.1"
            MYSQL_TCP_PORT: 3306
            MYSQL_DATABASE: "YTLockerDB"
            YOUTUBE_API_KEY: ""
            GO_API_HOST: ""
            GO_API_PORT: "8080"
            ADMIN_BEARER: "TEMP_ADMIN_BEARER"
        networks:
            - default

    react_web:
        build:
            reactlocker
        volumes:
            - ./reactlocker:/app
        ports:
            - 3000:3000
        environment:
            CHOKIDAR_USEPOLLING: "true"
            SKIP_PREFLIGHT_CHECK: "true"
        command: ["yarn", "start"]
        networks:
            - default

    story_book:
        build:
            reactlocker
        volumes:
            - ./reactlocker:/app
        ports:
            - 6006:6006
        environment:
            CHOKIDAR_USEPOLLING: "true"
            SKIP_PREFLIGHT_CHECK: "true"
        command: ["yarn", "storybook"]
        networks:
            - default


networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.26.0.0/16
                  gateway: 172.26.0.1
