version: "3.8"
services:
    db:
        build:
            mysqllocker
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: "YTLockerDB"
            MYSQL_ALLOW_EMPTY_PASSWORD: "YES"
            MYSQL_TCP_PORT: 3306
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
        expose:
            - 3306
        networks:
            - default
    api:
        build:
            golocker
        depends_on: 
            - db
        volumes:
            - ./golocker:/go/src/golocker
        ports:
            - 8080:8080
        environment:
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_HOST: "172.26.0.1"
            MYSQL_TCP_PORT: 3306
            MYSQL_DATABASE: "YTLockerDB"
            YOUTUBE_API_KEY: ""
            GO_API_HOST: ""
            GO_API_PORT: "8080"
        networks:
            - default

    hooks:
        build:
            hooklocker
        depends_on: 
            - db
        volumes:
            - ./hooklocker:/go/src/hooklocker
        ports:
            - 9090:9090
        environment:
            YOUTUBE_API_KEY: ""
            GO_API_HOST: ""
            GO_API_PORT: "9090"
        networks:
            - default

    web:
        build:
            reactlocker
        volumes:
            - ./reactlocker:/app
        ports:
            - 3000:3000
        environment:
            CHOKIDAR_USEPOLLING: "true"
        command: ["npm", "start"]
        networks:
            - default


networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.26.0.0/16
                  gateway: 172.26.0.1
