version: "3.8"
services:
    # api:
    #     image: golocker:latest
    db:
        image: mysql:8.0
        restart: always
        ports:
            - ${MYSQL_TCP_PORT}:${MYSQL_TCP_PORT}
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
            MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    web:
        build:
            reactlocker
        volumes:
            # to use local node_modules
            # - ./reactlocker/node_modules:/app/node_modules
            # to use container node_modules
            #- /app/node_modules
            - /app/node_modules
            - ./reactlocker:/app
        ports:
            - 3001:3000
        environment:
            CHOKIDAR_USEPOLLING: "true"
