// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/Killian264/YTLocker/golocker/models"
	mock "github.com/stretchr/testify/mock"
)

// IPlaylistData is an autogenerated mock type for the IPlaylistData type
type IPlaylistData struct {
	mock.Mock
}

// GetFirstYoutubeClientConfig provides a mock function with given fields:
func (_m *IPlaylistData) GetFirstYoutubeClientConfig() (*models.YoutubeClientConfig, error) {
	ret := _m.Called()

	var r0 *models.YoutubeClientConfig
	if rf, ok := ret.Get(0).(func() *models.YoutubeClientConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.YoutubeClientConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFirstYoutubeToken provides a mock function with given fields:
func (_m *IPlaylistData) GetFirstYoutubeToken() (*models.YoutubeToken, error) {
	ret := _m.Called()

	var r0 *models.YoutubeToken
	if rf, ok := ret.Get(0).(func() *models.YoutubeToken); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.YoutubeToken)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetYoutubeClientConfigByClientID provides a mock function with given fields: clientID
func (_m *IPlaylistData) GetYoutubeClientConfigByClientID(clientID string) (*models.YoutubeClientConfig, error) {
	ret := _m.Called(clientID)

	var r0 *models.YoutubeClientConfig
	if rf, ok := ret.Get(0).(func(string) *models.YoutubeClientConfig); ok {
		r0 = rf(clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.YoutubeClientConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetYoutubeTokenByAccessToken provides a mock function with given fields: accessToken
func (_m *IPlaylistData) GetYoutubeTokenByAccessToken(accessToken string) (*models.YoutubeToken, error) {
	ret := _m.Called(accessToken)

	var r0 *models.YoutubeToken
	if rf, ok := ret.Get(0).(func(string) *models.YoutubeToken); ok {
		r0 = rf(accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.YoutubeToken)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewYoutubeClientConfig provides a mock function with given fields: config
func (_m *IPlaylistData) NewYoutubeClientConfig(config *models.YoutubeClientConfig) error {
	ret := _m.Called(config)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.YoutubeClientConfig) error); ok {
		r0 = rf(config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewYoutubeToken provides a mock function with given fields: config
func (_m *IPlaylistData) NewYoutubeToken(config *models.YoutubeToken) error {
	ret := _m.Called(config)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.YoutubeToken) error); ok {
		r0 = rf(config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
