// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/Killian264/YTLocker/golocker/models"
	mock "github.com/stretchr/testify/mock"
)

// IPlaylistHelperData is an autogenerated mock type for the IPlaylistHelperData type
type IPlaylistHelperData struct {
	mock.Mock
}

// GetFirstYoutubeClientConfig provides a mock function with given fields:
func (_m *IPlaylistHelperData) GetFirstYoutubeClientConfig() (*models.YoutubeClientConfig, error) {
	ret := _m.Called()

	var r0 *models.YoutubeClientConfig
	if rf, ok := ret.Get(0).(func() *models.YoutubeClientConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.YoutubeClientConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFirstYoutubeToken provides a mock function with given fields:
func (_m *IPlaylistHelperData) GetFirstYoutubeToken() (*models.YoutubeToken, error) {
	ret := _m.Called()

	var r0 *models.YoutubeToken
	if rf, ok := ret.Get(0).(func() *models.YoutubeToken); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.YoutubeToken)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
