// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/Killian264/YTLocker/golocker/models"
	mock "github.com/stretchr/testify/mock"
)

// IPlaylistManager is an autogenerated mock type for the IPlaylistManager type
type IPlaylistManager struct {
	mock.Mock
}

// Create provides a mock function with given fields: user, playlist
func (_m *IPlaylistManager) Create(user *models.User, playlist *models.Playlist) (*models.Playlist, error) {
	ret := _m.Called(user, playlist)

	var r0 *models.Playlist
	if rf, ok := ret.Get(0).(func(*models.User, *models.Playlist) *models.Playlist); ok {
		r0 = rf(user, playlist)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Playlist)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.User, *models.Playlist) error); ok {
		r1 = rf(user, playlist)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: playlist, video
func (_m *IPlaylistManager) Insert(playlist *models.Playlist, video *models.Video) error {
	ret := _m.Called(playlist, video)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Playlist, *models.Video) error); ok {
		r0 = rf(playlist, video)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscribe provides a mock function with given fields: channel, playlist
func (_m *IPlaylistManager) Subscribe(channel *models.Channel, playlist *models.Playlist) {
	_m.Called(channel, playlist)
}

// Unsubscribe provides a mock function with given fields: channel, playlist
func (_m *IPlaylistManager) Unsubscribe(channel *models.Channel, playlist *models.Playlist) {
	_m.Called(channel, playlist)
}
