// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/Killian264/YTLocker/golocker/models"
	mock "github.com/stretchr/testify/mock"
)

// IYoutubeManager is an autogenerated mock type for the IYoutubeManager type
type IYoutubeManager struct {
	mock.Mock
}

// CreateVideo provides a mock function with given fields: videoID, channelID
func (_m *IYoutubeManager) CreateVideo(videoID string, channelID string) (*models.Video, error) {
	ret := _m.Called(videoID, channelID)

	var r0 *models.Video
	if rf, ok := ret.Get(0).(func(string, string) *models.Video); ok {
		r0 = rf(videoID, channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Video)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(videoID, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChannel provides a mock function with given fields: channelID
func (_m *IYoutubeManager) GetChannel(channelID string) (*models.Channel, error) {
	ret := _m.Called(channelID)

	var r0 *models.Channel
	if rf, ok := ret.Get(0).(func(string) *models.Channel); ok {
		r0 = rf(channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Channel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
