// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	youtube "google.golang.org/api/youtube/v3"
)

// IYoutubeHelper is an autogenerated mock type for the IYoutubeHelper type
type IYoutubeHelper struct {
	mock.Mock
}

// GetChannel provides a mock function with given fields: channelID
func (_m *IYoutubeHelper) GetChannel(channelID string) (*youtube.Channel, error) {
	ret := _m.Called(channelID)

	var r0 *youtube.Channel
	if rf, ok := ret.Get(0).(func(string) *youtube.Channel); ok {
		r0 = rf(channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*youtube.Channel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastVideosFromChannel provides a mock function with given fields: channelID, pageToken
func (_m *IYoutubeHelper) GetLastVideosFromChannel(channelID string, pageToken string) (*youtube.SearchListResponse, error) {
	ret := _m.Called(channelID, pageToken)

	var r0 *youtube.SearchListResponse
	if rf, ok := ret.Get(0).(func(string, string) *youtube.SearchListResponse); ok {
		r0 = rf(channelID, pageToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*youtube.SearchListResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(channelID, pageToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVideo provides a mock function with given fields: videoID
func (_m *IYoutubeHelper) GetVideo(videoID string) (*youtube.Video, error) {
	ret := _m.Called(videoID)

	var r0 *youtube.Video
	if rf, ok := ret.Get(0).(func(string) *youtube.Video); ok {
		r0 = rf(videoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*youtube.Video)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(videoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
