// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	youtube "google.golang.org/api/youtube/v3"
)

// IYoutubeService is an autogenerated mock type for the IYoutubeService type
type IYoutubeService struct {
	mock.Mock
}

// GetVideo provides a mock function with given fields: videoID, channelID
func (_m *IYoutubeService) GetVideo(videoID string, channelID string) (youtube.Video, error) {
	ret := _m.Called(videoID, channelID)

	var r0 youtube.Video
	if rf, ok := ret.Get(0).(func(string, string) youtube.Video); ok {
		r0 = rf(videoID, channelID)
	} else {
		r0 = ret.Get(0).(youtube.Video)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(videoID, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
