// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	youtube "google.golang.org/api/youtube/v3"
)

// IYoutubeService is an autogenerated mock type for the IYoutubeService type
type IYoutubeService struct {
	mock.Mock
}

// GetVideo provides a mock function with given fields: videoID
func (_m *IYoutubeService) GetVideo(videoID string) (*youtube.Video, error) {
	ret := _m.Called(videoID)

	var r0 *youtube.Video
	if rf, ok := ret.Get(0).(func(string) *youtube.Video); ok {
		r0 = rf(videoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*youtube.Video)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(videoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
